### ISSUE TITLE
object reference error on Windows 10

### ISSUE THREAD

**Issue by BoQsc** [Sgt-Nukem/UPnP_PortMapp0r#1]
```

C:\Users\vaida\Desktop\Minecraft server2>UPnP_PortMapp0r add 25565 tcp 192.168.0.105

UPnP_PortMapp0r - by Sgt. Nukem, version: 0.1.3.7
=================================================


Error: Could not add port mapping. Exception: Object reference not set to an instance of an object.
```

```

C:\Users\vaida\Desktop\Minecraft server2>UPnP_PortMapp0r "remove" "25565" "tcp"

UPnP_PortMapp0r - by Sgt. Nukem, version: 0.1.3.7
=================================================


Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at UPnP_PortMapp0r.Program.RemoveMapping(UPnPNAT upnpNAT, String[] args)
   at UPnP_PortMapp0r.Program.Main(String[] args)
```

**Comment by Sgt-Nukem** [comment]
Hi @BoQsc 

I added better exception handling and created a new release for you: https://github.com/Sgt-Nukem/UPnP_PortMapp0r/releases/tag/0.1.3.8-%CE%B2

You will now get a sane error message instead of the app crashing with an unhandled exception. :)


But the issue occurs when your router
- doesn't support UPnP
- has UPnP disabled
- had UPnP enabled but updating router state via UPnP disabled (i.e. "read-only" UPnP as security measure)


Please tell me if this helps.

**Comment by BoQsc** [comment]
@Sgt-Nukem 
Thanks for the error message improvement.

Everything works on the desktop computer that I own, the router that I have does support that.
This error appear on a laptop. The only difference, that it is a laptop, 
and its Windows 10 haven't been updated in a while.

It is under the same router, and I tested whole a lot, but without success to make UPnP_PortMapp0r work. Everything was unsuccessful on that laptop. 

If I have a chance, I'll try to use it on another laptop as well. Maybe my router can't respond to **UPnP_PortMapp0r** when the **UPnP_PortMapp0r** is running on a computer under **wifi** and not **ethernet connection**.

**Comment by Sgt-Nukem** [comment]
@BoQsc 

The NATUPNPLib library my code is wrapping has been redistributed by Microsoft since Windows XP. So I pretty much doubt that "Windows 10 not updated" is the culprit here.

While it *could* be, your router is disallowing UPnP via Wifi, I have my doubts there, too. As there is as much reason for a laptop to have smooth video calls via Skype (with ports forwarded) as there is for a desktop computer.
Maybe your router has separate settings for UPnP via Ethernet vs Wifi? What model is it?

Look at the concrete error message with the newer version of **UPnP_PortMapp0r**. I concluded (not completely sure, though) that E_USER_EXCEPTION is thrown by Microsoft's NATUPNPLib itself (before sending ANYTHING to the router AT ALL), while E_SERVICE_SPECIFIC_ERROR is thrown when the router responds to the network request with a "Sorry, this failed."

**Comment by Sgt-Nukem** [comment]
BTW, just for good measure, I would
- temporarily turn off the Window Firewall
- wait a minute (to let NATUPNPLib settle - it's trying to detect routers after all)
- then try **UPnP_PortMapp0r** again and see if anything differs

P.S.: Don't forget to turn on the firewall again!

**Comment by BoQsc** [comment]
> @BoQsc
> 
> The NATUPNPLib library my code is wrapping has been redistributed by Microsoft since Windows XP. So I pretty much doubt that "Windows 10 not updated" is the culprit here.

##  I saw that your project requires **Microsoft .NET Framework 4**, 
(https://www.microsoft.com/en-us/download/details.aspx?id=17851)


I tried to install it, the installer said:
```

Details

Microsoft .NET Framework 4 is already a part of this operating system.  You do not need to install the .NET Framework 4 redistributable. <A HREF="http://go.microsoft.com/fwlink/?LinkId=164207">More information</A>. 

Same or higher version of .NET Framework 4 has already been installed on this computer.
```
---


> While it _could_ be, your router is disallowing UPnP via Wifi, I have my doubts there, too. As there is as much reason for a laptop to have smooth video calls via Skype (with ports forwarded) as there is for a desktop computer.
> Maybe your router has separate settings for UPnP via Ethernet vs Wifi? What model is it?


## The model of the router
```
TP-LINK
N750 Wireless Dual Band Gigabit Router
Model No. TL-WDR4300
```

> Look at the concrete error message with the newer version of **UPnP_PortMapp0r**. I concluded (not completely sure, though) that E_USER_EXCEPTION is thrown by Microsoft's NATUPNPLib itself (before sending ANYTHING to the router AT ALL), while E_SERVICE_SPECIFIC_ERROR is thrown when the router responds to the network request with a "Sorry, this failed."

## I can't see more concrete error message, this is all I get:


```
C:\Users\vaida\Desktop>UPnP_PortMapp0r.exe add 25565 tcp 192.168.0.105

UPnP_PortMapp0r - by Sgt. Nukem, version: 0.1.3.8
=================================================

Error: Could not access static port mappings from NAT router. This can happen if it does not support UPnP, UPnP is not e
nabled, or its security settings disallows changes to port mappings via UPnP.



```









---

> BTW, just for good measure, I would
> 
> * temporarily turn off the Window Firewall
> * wait a minute (to let NATUPNPLib settle - it's trying to detect routers after all)
> * then try **UPnP_PortMapp0r** again and see if anything differs
> 
> P.S.: Don't forget to turn on the firewall again!

**Disabling Windows Firewall** was the first I tried. **No Luck, same error.**

```
Don't forget to turn on the firewall again!
```
Ahh, at least Microsoft does not re-enable it himself by force after certain time passed. 🙉

**Comment by BoQsc** [comment]
## In conclusion
Okey, it seems we have **3 laptops** that do get the **same error**.

And 1 desktop computer that actually can **set upnp ports without problems**.

Might be problems with the router?
I even connected the laptop with the ethernet cable, the same error appears.

## Update
I tried all of the many settings on a router, none lead to any success or make the error message go away.


So it is probably either some sneaky security setting in the router.  
Or something sneaky with Windows 10 on the laptops.

### Update 2

I've taken some cheap mini router, enabled upnp support in it.
And it seems that neither my laptop nor desktop computer was able to make any upnp rules.
I tried both Ethernet and Wireless connection.
**None worked.**


Btw I used older version of **UPnP_PortMapp0r**  just to make sure, the error message is the same.
```

UPnP_PortMapp0r - by Sgt. Nukem, version: 0.1.3.7
=================================================


Error: Could not add port mapping. Exception: Object reference not set to an instance of an object.

```
